spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daltan
    username: mynt_user
    password: 12345
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false